local _a=loadstring(game:HttpGet("https://github.com/Footagesus/WindUI/releases/latest/download/main.lua"))()
local _b=game:GetService("Players")
local _c=game:GetService("RunService")
local _d=game:GetService("Workspace")
local _e=_b.LocalPlayer
local _f=_e.Name
local _g={a=false,b=false,c=false,d=false,e=false,f=false,g="GUI",h="Top",i=false,j=false,k=false,l=nil}
local function _h(_i)if not _i then return nil end if _i:IsA("BasePart")then return _i.CFrame end if _i:IsA("Model")then if _i.PrimaryPart then return _i.PrimaryPart.CFrame end local _j,_k=pcall(function()return _i:GetPivot()end)if _j and _k then return _k end local _l=_i:FindFirstChildWhichIsA("BasePart",true)if _l then return _l.CFrame end end if _i:IsA("Attachment")then return _i.WorldCFrame end return nil end
local function _i()local _j=_d:FindFirstChild("Creatures")return _j and _j:FindFirstChild(_f)end
local function _j(_k)if not _k then return nil end local _l=_k:FindFirstChild("Body")if _l then local _m=_l:FindFirstChild("Mouth")if _m then return _m end end return _k:FindFirstChild("Mouth",true)end
local function _k(_l,_m)if not _l then return 0 end local _n=_l:FindFirstChild(_m)if not _n then return 0 end local _o=_n.Value return typeof(_o)=="number" and _o or(tonumber(_o)or 0)end
local function _l()local _m=_i()if not _m then return nil end return _k(_m:FindFirstChild("TotalStats"),"Hunger")end
local function _m(_n)local _o=_b:FindFirstChild(_n)if not _o then return 0 end local _p=_o:FindFirstChild("leaderstats")if not _p then return 0 end local _q=_p:FindFirstChild("Age")if not _q then return 0 end local _r=_q.Value return typeof(_r)=="number" and _r or(tonumber(_r)or 0)end
local function _n()local _o=_i()if not _o then return nil end return _o:FindFirstChild("HumanoidRootPart")or _o.PrimaryPart or _o:FindFirstChildWhichIsA("BasePart",true)end
local function _o(_p)local _q=_n()if not _q then return 0 end local _r=_p:FindFirstChild("HumanoidRootPart")or _p.PrimaryPart or _p:FindFirstChildWhichIsA("BasePart",true)if not _r then return 0 end return(_q.Position-_r.Position).Magnitude end
local function _p()local _q=_i()if not _q then return nil end local _r=_j(_q)if _r then local _s=_h(_r)if _s then return _s*CFrame.new(0,0,-0.5)end end local _t=_q:FindFirstChild("Body")if _t then for _,_u in ipairs({"Head","Face","Jaw","MouthPart","Tongue"})do local _v=_t:FindFirstChild(_u,true)if _v then local _w=_h(_v)if _w then return _w*CFrame.new(0,0,-0.8)end end end end local _x=_q:FindFirstChild("HumanoidRootPart")or _q.PrimaryPart or _q:FindFirstChildWhichIsA("BasePart",true)if _x then return _x.CFrame*CFrame.new(0,1,-2)end return _h(_q)end
local function _q()return _g.a or _g.b or _g.c or _g.d or _g.e end
local function _r()local _s=0 if _g.a then _s=_s+1 end if _g.b then _s=_s+1 end if _g.c then _s=_s+1 end if _g.d then _s=_s+1 end if _g.e then _s=_s+1 end return _s end
local _s={}
local function _t(_u)if _u=="Top"then return Vector3.new(0,3.6,0)end if _u=="Below"then return Vector3.new(0,-2.8,0)end if _u=="Left"then return Vector3.new(-3.8,1.2,0)end if _u=="Right"then return Vector3.new(3.8,1.2,0)end return Vector3.new(0,3.6,0)end
local function _u(_v)local _w=_s[_v]if not _w then return end if _w.Billboard then pcall(function()_w.Billboard:Destroy()end)end if _w.Highlight then pcall(function()_w.Highlight:Destroy()end)end _s[_v]=nil end
local function _v()for _w in pairs(_s)do _u(_w)end end
local function _w(_x)if not _x or not _x.Parent then return end if _x.Name==_f then return end local _y=_x:FindFirstChild("HumanoidRootPart")or _x.PrimaryPart or _x:FindFirstChildWhichIsA("BasePart",true)if not _y then return end _u(_x.Name)local _z=_r()local _A=_z>0 local _B=_g.f if not _A and not _B then return end local _C=_g.g=="GUI"local _D=_C and 58 or 52 local _E=_C and 3 or 2 local _F=math.max(_z*_D+(_z-1)*_E+8,20)local _G=_C and 18 or 16 local _H=nil local _I={}if _A then _H=Instance.new("BillboardGui")_H.Name="EliteESP"_H.Adornee=_y _H.Size=UDim2.new(0,_F,0,_G)_H.StudsOffset=_t(_g.h)_H.AlwaysOnTop=true _H.MaxDistance=300 _H.Parent=_y local _J=Instance.new("Frame")_J.Size=UDim2.new(1,0,1,0)_J.BackgroundTransparency=_C and 0.15 or 1 _J.BackgroundColor3=Color3.fromRGB(0,0,0)_J.BorderSizePixel=0 _J.Parent=_H if _C then local _K=Instance.new("UICorner")_K.CornerRadius=UDim.new(0,4)_K.Parent=_J end local _L=Instance.new("UIListLayout")_L.FillDirection=Enum.FillDirection.Horizontal _L.HorizontalAlignment=Enum.HorizontalAlignment.Center _L.VerticalAlignment=Enum.VerticalAlignment.Center _L.Padding=UDim.new(0,_E)_L.SortOrder=Enum.SortOrder.LayoutOrder _L.Parent=_J local _M=0 local function _N(_O,_P,_Q,_R)if not _R then return nil end _M=_M+1 local _S=Instance.new("TextLabel")_S.Name=_O _S.LayoutOrder=_M _S.Size=UDim2.new(0,_D,1,0)_S.BackgroundTransparency=1 _S.Text=_P..":--"_S.TextColor3=_Q _S.TextStrokeTransparency=0.4 _S.TextStrokeColor3=Color3.new(0,0,0)_S.Font=Enum.Font.GothamBold _S.TextSize=_C and 10 or 9 _S.TextXAlignment=Enum.TextXAlignment.Center _S.Parent=_J return _S end _I.MaxHealth=_N("MaxHealth","MaxHP",Color3.fromRGB(0,220,100),_g.a)_I.Health=_N("Health","HP",Color3.fromRGB(0,255,160),_g.b)_I.Hunger=_N("Hunger","Hunger",Color3.fromRGB(255,200,0),_g.c)_I.Age=_N("Age","Age",Color3.fromRGB(255,220,100),_g.d)_I.Distance=_N("Distance","Dist",Color3.fromRGB(140,190,255),_g.e)end local _T=nil if _B then _T=Instance.new("Highlight")_T.Name="EliteChams"_T.Adornee=_x _T.FillColor=Color3.fromRGB(255,40,40)_T.OutlineColor=Color3.fromRGB(255,80,80)_T.FillTransparency=0.7 _T.OutlineTransparency=0.4 _T.DepthMode=Enum.HighlightDepthMode.AlwaysOnTop _T.Parent=_x end _s[_x.Name]={Billboard=_H,Labels=_I,Highlight=_T,ActiveCount=_z,Style=_g.g}end
local function _x()local _y=_d:FindFirstChild("Creatures")if not _y then return end local _z=_r()local _A=_g.g for _,_B in ipairs(_y:GetChildren())do if _B.Name~=_f then local _C=_s[_B.Name]local _D=false if not _C then _D=true elseif _C.ActiveCount~=_z then _D=true elseif _C.Style~=_A then _D=true elseif _z>0 and(not _C.Billboard or not _C.Billboard.Parent)then _D=true elseif _g.f and(not _C.Highlight or not _C.Highlight.Parent)then _D=true end if _D then _w(_B)_C=_s[_B.Name]end if _C then if _C.Billboard and _C.Billboard.Parent then _C.Billboard.StudsOffset=_t(_g.h)end local _E=_B:FindFirstChild("TotalStats")local _F=_C.Labels or{}if _F.MaxHealth and _F.MaxHealth.Parent then _F.MaxHealth.Text="MaxHP:"..math.floor(_k(_E,"MaxHealth"))end if _F.Health and _F.Health.Parent then local _G=0 if _E then local _H=_E:FindFirstChild("Health")or _E:FindFirstChild("CurrentHealth")or _E:FindFirstChild("HP")if _H then _G=typeof(_H.Value)=="number" and _H.Value or(tonumber(_H.Value)or 0)end end if _G==0 then local _I=_B:FindFirstChildOfClass("Humanoid")if _I then _G=_I.Health end end _F.Health.Text="HP:"..math.floor(_G)end if _F.Hunger and _F.Hunger.Parent then _F.Hunger.Text="Hunger:"..math.floor(_k(_E,"Hunger"))end if _F.Age and _F.Age.Parent then _F.Age.Text="Age:"..math.floor(_m(_B.Name))end if _F.Distance and _F.Distance.Parent then _F.Distance.Text="Dist:"..math.floor(_o(_B))end if _g.f then if not _C.Highlight or not _C.Highlight.Parent then local _J=Instance.new("Highlight")_J.Name="EliteChams"_J.Adornee=_B _J.FillColor=Color3.fromRGB(255,40,40)_J.OutlineColor=Color3.fromRGB(255,80,80)_J.FillTransparency=0.7 _J.OutlineTransparency=0.4 _J.DepthMode=Enum.HighlightDepthMode.AlwaysOnTop _J.Parent=_B _C.Highlight=_J end elseif _C.Highlight and _C.Highlight.Parent then _C.Highlight:Destroy()_C.Highlight=nil end end end end for _K in pairs(_s)do if not _y:FindFirstChild(_K)then _u(_K)end end end
local function _y(_z)if not _z or not _z.Parent then return end local _A=_p()if not _A then return end pcall(function()if _z:IsA("BasePart")then _z.CanCollide=false _z.Anchored=false _z.CFrame=_A elseif _z:IsA("Model")then for _,_B in ipairs(_z:GetDescendants())do if _B:IsA("BasePart")then _B.CanCollide=false end end if _z.PivotTo then _z:PivotTo(_A)elseif _z.PrimaryPart then _z:SetPrimaryPartCFrame(_A)else local _C=_z:FindFirstChildWhichIsA("BasePart",true)if _C then _C.CFrame=_A end end end end)end
local function _z()local _A=_d:FindFirstChild("MapObjects")if not _A then return end local _B=_A:FindFirstChild("Food")if not _B then return end local _C=_B:FindFirstChild("DNA")if _C then _y(_C)end end
local function _A()local _B=_d:FindFirstChild("MapObjects")if not _B then return end local _C=_B:FindFirstChild("Food")if _C then local _D=_C:GetChildren()if _D[33]then _y(_D[33])end for _,_E in ipairs(_D)do if _E.Name~="DNA"then _y(_E)end end end local _F=_B:FindFirstChild("ExtraFood")if _F then local _G=_F:GetChildren()if _G[9]then _y(_G[9])end for _,_H in ipairs(_G)do _y(_H)end end end
local function _B()local _C=_d:FindFirstChild("MapObjects")if not _C then return false end local _D=_C:FindFirstChild("ExtraFood")if _D then local _E=_D:GetChildren()if #_E>0 then _y(_E[1])return true end end local _F=_C:FindFirstChild("Food")if _F then for _,_G in ipairs(_F:GetChildren())do if _G.Name~="DNA"then _y(_G)return true end end end return false end
local _C=0
local function _D()if not _g.k or _g.l==nil then return end local _E=_l()if _E==nil then return end if _E<_g.l then local _F=tick()if _F-_C>=0.4 then _C=_F _B()end end end
local _E=0
_c.Heartbeat:Connect(function()local _F=tick()if _F-_E<0.1 then return end _E=_F if _q()or _g.f then _x()elseif next(_s)then _v()end if _g.i then _z()end if _g.j then _A()end _D()end)
local _F=_a:CreateWindow({Title="Evolve | Made By ErickzzAlt",Icon="dna",Author="ErickzzzAlt",Folder="CreatureEliteHub",Theme="Dark",Size=UDim2.fromOffset(480,460)})
local _G=_F:Tab({Title="ESP",Icon="eye"})
_G:Section({Title="Esp Labels"})
_G:Toggle({Title="Max Health",Value=false,Flag="MaxHealthESP",Callback=function(_H)_g.a=_H _v()end})
_G:Toggle({Title="Health",Value=false,Flag="HealthESP",Callback=function(_H)_g.b=_H _v()end})
_G:Toggle({Title="Hunger",Value=false,Flag="HungerESP",Callback=function(_H)_g.c=_H _v()end})
_G:Toggle({Title="Age",Value=false,Flag="AgeESP",Callback=function(_H)_g.d=_H _v()end})
_G:Toggle({Title="Distance",Value=false,Flag="DistanceESP",Callback=function(_H)_g.e=_H _v()end})
_G:Section({Title="Visuals"})
_G:Toggle({Title="Chams",Value=false,Flag="Chams",Callback=function(_H)_g.f=_H if not _H then for _,_I in pairs(_s)do if _I.Highlight then pcall(function()_I.Highlight:Destroy()end)_I.Highlight=nil end end end _v()end})
_G:Dropdown({Title="ESP Style",Values={"GUI","Floating"},Value="GUI",Flag="ESPStyle",Callback=function(_H)_g.g=_H _v()end})
_G:Dropdown({Title="ESP Position",Values={"Top","Left","Right","Below"},Value="Top",Flag="ESPPosition",Callback=function(_H)_g.h=_H for _,_I in pairs(_s)do if _I.Billboard and _I.Billboard.Parent then _I.Billboard.StudsOffset=_t(_H)end end end})
local _H=_F:Tab({Title="Auto Farm",Icon="zap"})
_H:Section({Title="Bring"})
_H:Toggle({Title="Auto Bring DNA Crystals",Value=false,Flag="AutoBringDNA",Callback=function(_I)_g.i=_I end})
_H:Toggle({Title="Bring Food",Value=false,Flag="BringFood",Callback=function(_I)_g.j=_I end})
_H:Section({Title="Auto Eat"})
_H:Toggle({Title="Auto Eat",Value=false,Flag="AutoEat",Callback=function(_I)if _I and _g.l==nil then _a:Notify({Title="Auto Eat",Content="Set a threshold number first!",Duration=3})_g.k=false return end _g.k=_I end})
_H:Input({Title="amount of hunger to automatically eat",Placeholder="Example: 5",Flag="EatThreshold",Callback=function(_I)local _J=tonumber(_I)if _J then _g.l=_J _a:Notify({Title="Threshold Set",Content="Brings food only while Hunger < ".._J,Duration=2})else _g.l=nil _a:Notify({Title="Invalid",Content="Enter a valid number",Duration=2})end end})
_a:Notify({Title="Hub",Content="Welcome ".._f,Icon="check-circle",Duration=3})
_a:Notify({Title="Hub",Content="Suggestions? Comment on Scriptblox!",Icon="check-circle",Duration=8})